name: test
# prepare for releasing to prod:
#   convert solution to managed (using a build PowerPlatform environment for the conversion)
#   upload the solution to the GitHub artifacts and deploy to the PROD environment
on:
  release:
      types: [created]        

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/workflows/release-solution-to-prod.yml
        with:
          solution-folder: 'test'
          
