name: test
# prepare for releasing to prod:
#   convert solution to managed (using a build PowerPlatform environment for the conversion)
#   upload the solution to the GitHub artifacts and deploy to the PROD environment
on:
  release:
      types: [created]        

jobs:
  call-workflow:
    uses: ./.github/workflows/release-solution-to-prod.yml
    with:
      #solution_name: ALMLab       
      #solution_shipping_folder: out/ship/
      #solution_outbound_folder: out/solutions/
      #solution_source_folder: solutions/
      #solution_release_folder: out/release
      BUILD_ENVIRONMENT_URL: https://marcelbuild.crm.dynamics.com
      PRODUCTION_ENVIRONMENT_URL: https://marcelprod.crm.dynamics.com        
      CLIENT_ID: f6d88eaf-8e50-4b1f-93f2-b3af56880603       
      TENANT_ID: ec6b17bb-11d0-4195-abd0-521c69a5d1fd                
      envSecret: ${{ secrets.PowerPlatformSPN }}
