name: test
# prepare for releasing to prod:
#   convert solution to managed (using a build PowerPlatform environment for the conversion)
#   upload the solution to the GitHub artifacts and deploy to the PROD environment
on:
  workflow_dispatch:
  
  inputs:
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: ALMLab
       #Do Not change these values
      solution_shipping_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: out/ship/
      solution_outbound_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_source_folder: 
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: solutions/
      solution_release_folder:
       description: 'folder where the released binaries are going to be hosted *do not change*'
       required: true
       default: out/release

env:
#edit your values here
  BUILD_ENVIRONMENT_URL: 'https://marcelbuild.crm.dynamics.com'
  PRODUCTION_ENVIRONMENT_URL: 'https://marcelprod.crm.dynamics.com'
  CLIENT_ID: 'f6d88eaf-8e50-4b1f-93f2-b3af56880603'
  TENANT_ID: 'ec6b17bb-11d0-4195-abd0-521c69a5d1fd'
  SOLUTION: ${{ github.event.inputs.solution_name }}

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ github.event.inputs.solution_name }}
          TAGS: ${{ github.event.inputs.solution_shipping_folder }}
          ENVIRONMENT: ${{ github.event.inputs.solution_outbound_folder }}
